### ISSUE TITLE
Processing samples from multiple individuals for joint analysis

### ISSUE THREAD

**Issue by bioinfnewb** [LuyiTian/scPipe#114]
Hi,

I would like to process the 10X data from Census of Immune Cells (HCA preview dataset). The data is as follows:

Cord blood (CB) 10X measurements 8 individuals (donor)
Bone Marrow (BM) 10X measurements 8 individuals (donor)

Given that there are multiple samples from multiple individuals, is there are way to have a single gene count matrix that will contain information for all individuals? I understand that the **sc_exon_mapping** function takes in multiple BAM files, and this approach can be used when dealing with multiple libraries/samples for 1 individual. But what can be done when there are more individuals? I would like to do something similar to cellranger's **cell aggr** function.

My aim is to perform a joint analysis of multiple datasets to facilitate the identification of rare cell-types, if any.

Thanks!

**Comment by LuyiTian** [comment]
The reads, if I remember correctly, have been demultiplexed by samples, so that you can process them separately, and give different name prefix in `sc_detect_bc`, such as `prefix="BM01_"`, `prefix="CB03_"` for each sample. Then you can merge them and they won't have duplicated names.

**Comment by LuyiTian** [comment]
I processed the spleen data: `https://github.com/LuyiTian/HCA_Previewdata` on the HCA-CZI conference last year, the time when they release these datasets. I did not process the BM data because I cannot log back to our server in the conference centre and I don't have much space on my laptop.

**Comment by bioinfnewb** [comment]
Thanks Luyi. So just to confirm, I will end up with 8 gene counts tables for the CB samples (and 8 for the BM samples). Then I can merge the 8 CB gene counts tables into a single matrix. Is there a way to this in scPipe? I know Seurat does it, so just want to double check.

Thanks!

**Comment by LuyiTian** [comment]
unfortunately not. I used to have a combine-object function early days and then I would though SCE would provide and general function to do that so I removed that function. However they don't, and I asked Aaron, he doesn't want to write such a function because he believes it will be misleading anyway. 

so you can just merge the gene count matrix and QC data.frame separately, using standard R function.

**Comment by bioinfnewb** [comment]
No problem. Thanks again for getting back to me!
