### ISSUE TITLE
Column length error

### ISSUE THREAD

**Issue by audreystott** [LuyiTian/scPipe#117]
Hi Shian

I'm faced with another error message while running the sc_count_aligned_bam function:

Error in mutate_impl(.data, dots) :
  Column `gene_id` must be length 324663 (the number of rows) or one, not 324662

Tried googling and can't find a definite answer. Please help, thank you!

Kind regards
Audrey

**Comment by Shians** [comment]
Hi Audrey,

It looks like I need to do some work to make things work with this annotation. GFF formats are highly variable and I tested only on human and mouse annotations. I will update scPipe to handle annotations of this form soon.

Kind regards,
Shian

**Comment by Shians** [comment]
I've updated the code to somewhat handle this annotation. The file still needs to be external altered as per #116, and a small number of the entries could not be properly associated with a GeneID as per #119. Otherwise it should get you over this hurdle.
