### ISSUE TITLE
Trailing whitespace in sample annotation causes bug

### ISSUE THREAD

**Issue by Shians** [LuyiTian/scPipe#14]
If the sample annotation file ends with >2 trailing newlines then `Barcode::read_anno` will read in and record blank entries, this leads to columns without headers in `gene_counts` and rows without row names in `stat/cell_stat.csv`. I think this may cause unexpected behaviour for anything that uses `while(std::getline(...))` as its guard.

**Comment by LuyiTian** [comment]
actually, the bug has been solved in scPipeCPP but it's hard to copy&paste the code directly since there are a lot difference in the two repo.
