### ISSUE TITLE
Error in sc_trim_barcode

### ISSUE THREAD

**Issue by satzel** [LuyiTian/scPipe#143]
Hi,

I am trying to run scPipe and run into an error when executing:

```
sc_trim_barcode(file.path(data_dir,"combined.fastq"),
                fq_R1,
                fq_R2,
                read_structure = read_structure)
```

The error I get is:

_Error in rcpp_sc_trim_barcode_paired(outfq, r1, r2, read_structure$bs1,  : 
Can't open file: ~/some/path/combined.fastq_

data_dir is correctly set.

I don't quite understand, if R is supposed to create this file or if I have to create it as an empty file (tried both, didn't change anything) or what else I have to do, to make it run.

Any help would be appreciated 
cheers
saskia

**Comment by PeteHaitch** [comment]
Can you please post the output of running `file.path(data_dir,"combined.fastq")`.

**Comment by satzel** [comment]
Thanks for your quick reply @PeteHaitch

```
 file.path(data_dir,"combined.fastq")
[1] "~/some/path/combined.fastq"

```

as a side note, when I keep going in the script and try this

`
barcode_anno = "sample_index.csv"
exon_anno = "Annotation/Homo_sapiens.GRCh38.91.gff3"

# detect 10X barcodes and generate sample_index.csv file
sc_detect_bc(
	infq = combined_fastq,
	outcsv = barcode_anno,       # bacode annotation output file name
	bc_len = read_structure$bl2, # 16bp barcode
	max_reads = 5000000,         # only process first 5 million reads
	min_count = 100              # discard cell barcodes with few than 100 hits
)
`
it runs without error and the csv file is created (its empty cause the input is not right but the file is created) in the same folder I am trying to run the other command it. so it doesn't seem an issue with the output folder.

**Comment by PeteHaitch** [comment]
Does the directory `~/some/path` actually exist on your computer?
I'm guessing it doesn't.
Have you copy+pasted this code from somewhere?
If you want to use this exact code, then `data_dir` has to be a real directory on your computer.

**Comment by satzel** [comment]
@PeteHaitch yes it does exist on my computer

**Comment by PeteHaitch** [comment]
Okay.
Can you please supply the output of `sessionInfo()` and, ideally, a minimal reproducible example (including example FASTQ file).
It's a bit hard to help further without these details.

**Comment by satzel** [comment]
thanks @PeteHaitch I managed to figure it out, even though all the paths were correct it doesn't run when there is a ~ in the path...

**Comment by Shians** [comment]
Tilde expansion should work, I may have missed it in certain functions will leave myself a note here to check it.
