### ISSUE TITLE
sc_demultiplex crashes R

### ISSUE THREAD

**Issue by klprint** [LuyiTian/scPipe#26]
Hi!

I am trying to use your tool to analyse my single cell RNAseq data. I adhered strictly to your documentation and I was able to generate all intermediate files till the out.map.bam file.
When I then try to demultiplex the bam file using sc_demultiplex, the R session crashes without any prior warning.

The data should contain about 1300 cells. According to the printed stats before sc_demultiplex, everything worked fine and the package-integrated example data, I can analyse without any problem.
Any suggestions?

**Comment by klprint** [comment]
BTW:

```r
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] C

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] scPipe_0.99.16      ggplot2_2.2.1       Biobase_2.37.2      BiocGenerics_0.23.0

loaded via a namespace (and not attached):
 [1] nlme_3.1-131         bitops_1.0-6         destiny_2.5.6        pbkrtest_0.4-7       xts_0.10-0           bit64_0.9-7         
 [7] RColorBrewer_1.1-2   progress_1.1.2       tools_3.4.1          backports_1.1.0      R6_2.2.2             rpart_4.1-11        
[13] Hmisc_4.0-3          DBI_0.7              lazyeval_0.2.0       mgcv_1.8-18          colorspace_1.3-2     nnet_7.3-12         
[19] sp_1.2-5             gridExtra_2.2.1      smoother_1.1         prettyunits_1.0.2    GGally_1.3.2         bit_1.1-12          
[25] curl_2.8.1           compiler_3.4.1       quantreg_5.33        htmlTable_1.9        SparseM_1.77         scales_0.4.1        
[31] checkmate_1.8.3      DEoptimR_1.0-8       lmtest_0.9-35        robustbase_0.92-7    proxy_0.4-17         stringr_1.2.0       
[37] digest_0.6.12        foreign_0.8-69       minqa_1.2.4          base64enc_0.1-3      pkgconfig_2.0.1      htmltools_0.3.6     
[43] lme4_1.1-13          htmlwidgets_0.9      rlang_0.1.2          TTR_0.23-2           RSQLite_2.0          FNN_1.1             
[49] zoo_1.8-0            mclust_5.3           acepack_1.4.1        car_2.1-5            RCurl_1.95-4.8       magrittr_1.5        
[55] Formula_1.2-2        Matrix_1.2-11        Rcpp_0.12.12         munsell_0.4.3        S4Vectors_0.15.5     stringi_1.1.5       
[61] MASS_7.3-47          zlibbioc_1.23.0      Rtsne_0.13           plyr_1.8.4           grid_3.4.1           blob_1.1.0          
[67] lattice_0.20-35      splines_3.4.1        knitr_1.17           igraph_1.1.2         boot_1.3-20          biomaRt_2.33.4      
[73] stats4_3.4.1         XML_3.98-1.9         latticeExtra_0.6-28  data.table_1.10.4    laeken_0.4.6         vcd_1.4-3           
[79] nloptr_1.0.4         MatrixModels_0.4-1   VIM_4.7.0            gtable_0.2.0         reshape_0.8.7        assertthat_0.2.0    
[85] RcppEigen_0.3.3.3.0  e1071_1.6-8          class_7.3-14         survival_2.41-3      tibble_1.3.4         AnnotationDbi_1.39.2
[91] memoise_1.1.0        IRanges_2.11.12      cluster_2.0.6        Rhtslib_1.9.2       
```

**Comment by LuyiTian** [comment]
So what protocol does this data generated from, Drop-seq or CEL-seq or...? Can you give me the parameter you used for each step?

`sc_demultiplex ` evolves the cell barcode annotation file. can you double check your annotation is in the same format as https://github.com/LuyiTian/scPipe/blob/master/inst/extdata/barcode_anno.csv. 

Also, check the bam file. You can convert it to sam file and print a few lines to see if it looks normal. check the read name to see if there are cell barcode and UMI. the read name should follows the pattern: {cellbarcode}_{UMI}#{original read name}. after exon_mapping, a normal record looks like:

> AAAGTCAA_AACTCA#SIMULATE_SEQ::007::000::0013::10 0 ERCC-00171 142 40 73M * 0 0 GCCTCGGGAATAAGCTGACGGTGACAAGGTTTCCCCCTAATCGAGACGCTGCAATAACACAGGGGCATACAGT AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA HI:i:1 NH:i:1 NM:i:0 GE:Z:ERCC-00171 YC:Z:AAAGTCAA YM:Z:AACTCA YE:i:-364

with the cell barcode in `YC` tag, UMI in `YM` tag and gene name in `GE` tag.

**Comment by klprint** [comment]
We use a ICELL8 microwell system, the reads are compatible with scPipe because they are close to CEL-seq. 
Interestingly, samtools complains about the BAM file after exon mapping as follows:

```bash
> samtools view out.map.bam
[E::sam_format1] Corrupted aux data for read TTGGCCAGCTA_GTTCAGGGTGCTT
samtools view: writing to standard output failed: Invalid argument
```

The alignment BAM file looks perfectly fine:

```bash
> samtools view out.aln.bam
GAACCTTCGTA_AAGCTGGTCTGAG	0	10	105847035	40	65M	*	0	0	CAAGAGAGAGAAGAGGCTCAAAGGCTCTACAAAAAGAAAAAAATGGAAGCTTTCAAAATACTGAG	///E/E/EEE//E/AEEEE6//EEEEEE/E///EEEE/EA/A/EAEA/EEE/E<////E/EA<AE	HI:i:1	NH:i:1	NM:i:0
GGTCATCATCT_CTTTAAGTTTCGT	0	15	76905858	40	65M	*	0	0	GTTGTGGCTGGTGGGGGCAGAATTGACAAGCCTATCTTAAAGGCTGGCCGTGCCTACCACAAGTA	AAAEEEEEEEEEEE6EEEAEEEEEEEEEEEEEEEEEEEEEEEAEEAAEEEEAEEEEEEEEEEEEE	HI:i:1	NH:i:1	NM:i:0
```

For convenience, I attach the HTML export of my Rnotebook. Maybe you find some mistake.


[scPipe_run.nb.txt](https://github.com/LuyiTian/scPipe/files/1262794/scPipe_run.nb.txt)

**Comment by LuyiTian** [comment]
umm... you out.aln.bam looks unusual. GAACCTTCGTA_AAGCTGGTCTGAG should not be the whole read name, The read name should be GAACCTTCGTA_AAGCTGGTCTGAG#{raw_read_name_from_fastq}. Did you remove them? 

I know why R crashes without any notice. I think scPipe got the same error as `samtools view`. But, the scPipe uses Rhtslib for bam IO, and Rhtslib is barely a wrapper of the htslib C library, without using the R error handling system. So when the error occurs the R does not know how to respond, and simply stop and crash without any error message.

I checked your html. Is this the code you used the generate the data? If so then the UMI length does not match the result you pasted:
```
sc_exon_mapping(file.path(data_dir, "out.aln.bam"),
                file.path(data_dir, "out.map.bam"),
                file.path("Mus_musculus.GRCm38.90.chr.gff3"),
                bc_len = 11,
                UMI_len = 14)
```

In `TTGGCCAGCTA_GTTCAGGGTGCTT`, `GTTCAGGGTGCTT` is 13bp, not 14. Can you check your argument for function `sc_trim_barcode`.

The error `Corrupted aux data for read TTGGCCAGCTA_GTTCAGGGTGCTT` means the string in bam tag is either empty or not ended with a null terminator ('\0'). If in the `sc_trim_barcode` you set the length of UMI to be 13 and later on you use 14 in sc_exon_mapping, the program will use the index that out of bounds, which is not ended with a null terminator. Then you will get the error message on samtools.

**Comment by klprint** [comment]
Just before reading your answer I came across the fact that the UMI is too short. I really appreciate your effort in helping me out! I will check the settings and rerun the generation of the combined fastq file! Many thanks, I will let you know if it is working out.

**Comment by LuyiTian** [comment]
Thank you for pointing that out. I need to write more error handling functions in my pipeline.

The read structure is 0-indexed. so for bs2=0,bl2=11 it means find index-on-read2 from 0 and up to 11 base pair, which would be [0,10]. Therefore if the UMI comes after index-on-read2, then it should start from 11 not 12. so your argument should be:

                read_structure = list(bs1 = -1,
                                      bl1 = 0,
                                      bs2 = 0,
                                      bl2 = 11,
                                      us = 11, ul = 14)

you don't have to set bl1=2 if you don't have bl1. I set bl1=2 to trim the first 2bp is just because in our sequence data the base quality for first several base pairs is not very good so I trimmed them off.

also in scPipe the read1 is the longer read with the transcript. sometimes, depending on the protocol, the fastq from sequencer will have read2 to be the longer read contains transcript. you need to swap when you specify the r1,r2 in `sc_trim_barcode`.

I will add them to the doc so others won't be confused. Thank you for trying to run the package.

**Comment by klprint** [comment]
Hi!
The pipeline worked now. I changed the start index of the UMI and things worked out. Thanks a lot!
The only issue, probably due to limited RAM on my computer, was a two times abort when I tried to count the UMIs. But a restart opened up enough RAM to let the program run through.

Great work. It generated very nicely fitted results to a colleague of mine, who used a different approach.
