### ISSUE TITLE
ERROR: dependency ‘Rhtslib’ is not available for package ‘scPipe’

### ISSUE THREAD

**Issue by steve-englart** [LuyiTian/scPipe#27]
I am having an issue setting up a conda environment using 
R version 3.4.1 (2017-06-30) -- "Single Candle". 

Note I can install  Rsamtools  version  1.28.0, that I think is like Rhtslib with more stuff, so puzzled why this fails. Any help appreciated. 
``

trying URL 'https://bioconductor.org/packages/3.5/bioc/src/contrib/_1.8.0.tar.gz'
Content type 'application/x-gzip' length 2896075 bytes (2.8 MB)

downloaded 2.8 MB

Installing Rhtslib
'/data/opt/conda/envs/R_scPipe/lib/R/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmpy0oYz7/devtools300445dbc356/Rhtslib'  \
  --library='/data/opt/conda/envs/R_scPipe/lib/R/library' --install-tests 

* installing *source* package ‘Rhtslib’ ...
** libs
/bin/sh: 1: [: 0: unexpected operator
running configuration...
cd ./htslib/ && ./configure --disable-dependency-tracking \
--prefix="/data/opt/conda/envs/R_scPipe/lib/R/library/Rhtslib" \
CC="`"/data/opt/conda/envs/R_scPipe/lib/R/bin/R" CMD config CC`" CFLAGS="`"/data/opt/conda/envs/R_scPipe/lib/R/bin/R" CMD config CFLAGS` `"/data/opt/conda/envs/R_scPipe/lib/R/bin/R" CMD config CPICFLAGS`" \
LDFLAGS="`"/data/opt/conda/envs/R_scPipe/lib/R/bin/R" CMD config LDFLAGS`" CPPFLAGS="`"/data/opt/conda/envs/R_scPipe/lib/R/bin/R" CMD config CPPFLAGS`" CPP="`"/data/opt/conda/envs/R_scPipe/lib/R/bin/R" CMD config CPP`"
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for style of include used by make... GNU
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/tmp/Rtmpy0oYz7/devtools300445dbc356/Rhtslib/src/htslib':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
Makevars:44: recipe for target 'htslib/libhts.la' failed
make: *** [htslib/libhts.la] Error 1
ERROR: compilation failed for package ‘Rhtslib’
* removing ‘/data/opt/conda/envs/R_scPipe/lib/R/library/Rhtslib’
Installation failed: Command failed (1)
Skipping install of 'scales' from a cran remote, the SHA1 (0.5.0) has not changed since last install.
  Use `force = TRUE` to force installation
'/data/opt/conda/envs/R_scPipe/lib/R/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  '/tmp/Rtmpy0oYz7/devtools30042f71641f/LuyiTian-scPipe-cc42bba'  \
  --library='/data/opt/conda/envs/R_scPipe/lib/R/library' --install-tests 

ERROR: dependency ‘Rhtslib’ is not available for package ‘scPipe’
* removing ‘/data/opt/conda/envs/R_scPipe/lib/R/library/scPipe’
Installation failed: Command failed (1)
> 
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 17.04

Matrix products: default
BLAS: /data/opt/conda/envs/R_scPipe/lib/R/lib/libRblas.so
LAPACK: /data/opt/conda/envs/R_scPipe/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_AU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_AU.UTF-8        LC_COLLATE=en_AU.UTF-8    
 [5] LC_MONETARY=en_AU.UTF-8    LC_MESSAGES=en_AU.UTF-8   
 [7] LC_PAPER=en_AU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_AU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.3.1           compiler_3.4.1       R6_2.2.2            
 [4] BiocInstaller_1.26.1 tools_3.4.1          withr_2.0.0         
 [7] curl_2.8.1           memoise_1.1.0        knitr_1.17          
[10] git2r_0.19.0         digest_0.6.12        devtools_1.13.3     
> 

> as.data.frame(installed.packages()[,c(1,3:4)])
                          Package   Version    Priority
acepack                   acepack     1.4.1        <NA>
AnnotationDbi       AnnotationDbi    1.38.2        <NA>
assertthat             assertthat     0.2.0        <NA>
backports               backports     1.1.0        <NA>
base                         base     3.4.1        base
base64enc               base64enc     0.1-3        <NA>
BH                             BH  1.62.0-1        <NA>
bindr                       bindr       0.1        <NA>
bindrcpp                 bindrcpp       0.2        <NA>
Biobase                   Biobase    2.36.2        <NA>
BiocGenerics         BiocGenerics    0.22.0        <NA>
BiocInstaller       BiocInstaller    1.26.1        <NA>
BiocParallel         BiocParallel    1.10.1        <NA>
biomaRt                   biomaRt    2.32.1        <NA>
Biostrings             Biostrings    2.44.2        <NA>
bit                           bit    1.1-12        <NA>
bit64                       bit64     0.9-7        <NA>
bitops                     bitops     1.0-6        <NA>
blob                         blob     1.1.0        <NA>
boot                         boot    1.3-20 recommended
car                           car     2.1-5        <NA>
checkmate               checkmate     1.8.3        <NA>
class                       class    7.3-14 recommended
cluster                   cluster     2.0.6 recommended
colorspace             colorspace     1.3-2        <NA>
compiler                 compiler     3.4.1        base
curl                         curl     2.8.1        <NA>
data.table             data.table    1.10.4        <NA>
datasets                 datasets     3.4.1        base
DBI                           DBI     0.6-1        <NA>
dbplyr                     dbplyr     1.1.0        <NA>
DEoptimR                 DEoptimR     1.0-8        <NA>
destiny                   destiny     2.4.5        <NA>
devtools                 devtools    1.13.3        <NA>
dichromat               dichromat     2.0-0        <NA>
digest                     digest    0.6.12        <NA>
dplyr                       dplyr     0.7.0        <NA>
e1071                       e1071     1.6-8        <NA>
evaluate                 evaluate    0.10.1        <NA>
FNN                           FNN       1.1        <NA>
foreign                   foreign    0.8-69 recommended
Formula                   Formula     1.2-2        <NA>
futile.logger       futile.logger     1.4.3        <NA>
futile.options     futile.options     1.0.0        <NA>
GenomeInfoDb         GenomeInfoDb    1.12.2        <NA>
GenomeInfoDbData GenomeInfoDbData    0.99.0        <NA>
GenomicRanges       GenomicRanges    1.28.4        <NA>
GGally                     GGally     1.3.2        <NA>
ggplot2                   ggplot2     2.2.1        <NA>
git2r                       git2r    0.19.0        <NA>
glue                         glue     1.1.1        <NA>
graphics                 graphics     3.4.1        base
grDevices               grDevices     3.4.1        base
grid                         grid     3.4.1        base
gridBase                 gridBase     0.4-7        <NA>
gridExtra               gridExtra     2.2.1        <NA>
gtable                     gtable     0.2.0        <NA>
highr                       highr       0.6        <NA>
Hmisc                       Hmisc     4.0-3        <NA>
htmlTable               htmlTable       1.9        <NA>
htmltools               htmltools     0.3.6        <NA>
htmlwidgets           htmlwidgets       0.9        <NA>
httr                         httr     1.3.1        <NA>
igraph                     igraph     1.1.2        <NA>
IRanges                   IRanges    2.10.3        <NA>
irlba                       irlba     2.2.1        <NA>
jsonlite                 jsonlite       1.5        <NA>
knitr                       knitr      1.17        <NA>
labeling                 labeling       0.3        <NA>
laeken                     laeken     0.4.6        <NA>
lambda.r                 lambda.r     1.1.9        <NA>
lattice                   lattice   0.20-35 recommended
latticeExtra         latticeExtra    0.6-28        <NA>
lazyeval                 lazyeval     0.2.0        <NA>
lme4                         lme4    1.1-13        <NA>
lmtest                     lmtest    0.9-35        <NA>
magrittr                 magrittr       1.5        <NA>
markdown                 markdown       0.8        <NA>
MASS                         MASS    7.3-47        <NA>
Matrix                     Matrix    1.2-11 recommended
MatrixModels         MatrixModels     0.4-1        <NA>
mclust                     mclust       5.3        <NA>
memoise                   memoise     1.1.0        <NA>
methods                   methods     3.4.1        base
mgcv                         mgcv    1.8-19 recommended
mime                         mime       0.5        <NA>
minqa                       minqa     1.2.4        <NA>
munsell                   munsell     0.4.3        <NA>
nlme                         nlme   3.1-131 recommended
nloptr                     nloptr     1.0.4        <NA>
nnet                         nnet    7.3-12 recommended
openssl                   openssl     0.9.6        <NA>
parallel                 parallel     3.4.1        base
pbkrtest                 pbkrtest     0.4-7        <NA>
pkgconfig               pkgconfig     2.0.1        <NA>
plogr                       plogr     0.1-1        <NA>
plyr                         plyr     1.8.4        <NA>
prettyunits           prettyunits     1.0.2        <NA>
progress                 progress     1.1.2        <NA>
proxy                       proxy    0.4-17        <NA>
purrr                       purrr   0.2.2.2        <NA>
quantreg                 quantreg      5.33        <NA>
R6                             R6     2.2.2        <NA>
RColorBrewer         RColorBrewer     1.1-2        <NA>
Rcpp                         Rcpp   0.12.12        <NA>
RcppEigen               RcppEigen 0.3.3.3.0        <NA>
RCurl                       RCurl  1.95-4.8        <NA>
reshape                   reshape     0.8.7        <NA>
reshape2                 reshape2     1.4.2        <NA>
rlang                       rlang     0.1.1        <NA>
robustbase             robustbase    0.92-7        <NA>
rpart                       rpart    4.1-11 recommended
Rsamtools               Rsamtools    1.28.0        <NA>
RSQLite                   RSQLite       2.0        <NA>
rstudioapi             rstudioapi       0.6        <NA>
Rtsne                       Rtsne      0.13        <NA>
S4Vectors               S4Vectors    0.14.3        <NA>
scales                     scales     0.5.0        <NA>
scatterplot3d       scatterplot3d    0.3-40        <NA>
smoother                 smoother       1.1        <NA>
snow                         snow     0.4-2        <NA>
sp                             sp     1.2-5        <NA>
SparseM                   SparseM      1.77        <NA>
splines                   splines     3.4.1        base
statmod                   statmod    1.4.30        <NA>
stats                       stats     3.4.1        base
stats4                     stats4     3.4.1        base
stringi                   stringi     1.1.5        <NA>
stringr                   stringr     1.2.0        <NA>
survival                 survival    2.41-3 recommended
tcltk                       tcltk     3.4.1        base
tibble                     tibble     1.3.3        <NA>
tools                       tools     3.4.1        base
TTR                           TTR    0.23-2        <NA>
utils                       utils     3.4.1        base
vcd                           vcd     1.4-3        <NA>
VIM                           VIM     4.7.0        <NA>
viridis                   viridis     0.4.0        <NA>
viridisLite           viridisLite     0.2.0        <NA>
whisker                   whisker     0.3-2        <NA>
withr                       withr     2.0.0        <NA>
XML                           XML  3.98-1.7        <NA>
xts                           xts    0.10-0        <NA>
XVector                   XVector    0.16.0        <NA>
yaml                         yaml    2.1.14        <NA>
zlibbioc                 zlibbioc    1.22.0        <NA>
zoo                           zoo     1.8-0        <NA>

**Comment by LuyiTian** [comment]
I guess that would be the  errors:

> checking whether we are cross compiling... configure: error: in /tmp/Rtmpy0oYz7/devtools300445dbc356/Rhtslib/src/htslib': configure: error: cannot run C compiled programs. If you meant to cross compile, use--host'.
> See `config.log' for more details

I am not sure how to, but can you add the --host tag and see if that work? Also, can you find the config.log files?

The relationship between Samtools and Htslib is pretty messy. Previously there are only Samtools and then Htslib been separated as the backend. But it is not separated that well and the Htslib is poorly documented. Usually, Samtools have much more error handling. So I am not surprised they would have different behaviors.

**Comment by steve-englart** [comment]
Okay, thanks for the feedback. Yep I will look at few things including the --host tag and log files. The compile process deletes the log, so will need to do some research on how to keep it from deletion. 

I do realise that you may not be able to help with this as it does look like a library issue, and not your application.  I can also skip conda, but we are trying to reduce software surface area and allow for repeatability, and think conda may help with this. Conda does need to work though.

Cheers,
Steve

**Comment by LuyiTian** [comment]
Sorry I am not very familiar with Conda. But if you are thinking about the dependency and installation issue for many software that runs on the different platforms using different libraries, I would recommend Docker. It is like a lightweight version of a virtual machine. Such code will install a Picard docker runnable app: https://github.com/LuyiTian/NGS_docker/blob/master/dockerfiles/picard_Dockerfile, which will be independent of the running environment.

**Comment by steve-englart** [comment]
Hi Luyi,

Thanks for considering my running options with scPipe. Last week I
attempted to install the software on several different machines. I was
using conda as this is supported on any platform.

It would be wonderful if Docker was supported on HPC but sadly its not at
the moment. I have had some success but its still not consistent, as I can
get it work on some HPC and local laptop, but not other HPC platforms.

I think that R-3.4.x is relatively new, and not supported with the vast
libraries available for conda R-3.3.2. Bioconductor for one is missing. So
thus under conda you need to compile the required packages. This is the
problem as platform specific compiler flags, set by configure that
introduce a lot of variability.

Eventually conda's R-3.4.1 and associated libraries will stabilise and
become available, and hopefully scPipe will work with conda and many
hardware platforms without issue.

Cheers,
Steve
