### ISSUE TITLE
Defaults on create_report inside create_sce_by_dir not sensible

### ISSUE THREAD

**Issue by Shians** [LuyiTian/scPipe#32]
[The current defaults](https://github.com/LuyiTian/scPipe/blob/master/R/sc_workflow.R#L83) are all 1's, this doesn't really reflect a realistic set of default values. Maybe we should use CelSeq defaults or just leave it as NA?

**Comment by LuyiTian** [comment]
yes, your are right. now `create_report` can accept default values, such as `create_report(sample_name = "CB51",outdir = "~/data/CB51",organism = "mmusculus_gene_ensembl",gene_id_type = "ensembl_gene_id")`

**Comment by LuyiTian** [comment]
all default values of barcode and UMIs are set to zero in the report
