### ISSUE TITLE
Possible logic error in Barcode::get_closest_match?

### ISSUE THREAD

**Issue by Shians** [LuyiTian/scPipe#75]
Hi Luyi,

I am looking at the code here: https://github.com/LuyiTian/scPipe/blob/master/src/cellbarcode.cpp#L67-L104

I interpret `sml1st` as the smallest hamming distance and `sml2ed` as the second smallest. So I am guessing the intention of this code is to: "find the barcode with the smallest hamming distance and return it, [if there is a second barcode with the same hamming distance then return an empty string](https://github.com/LuyiTian/scPipe/blob/master/src/cellbarcode.cpp#L95-L102)".

But from this chunk

    tmp = hamming_distance(barcode, bc_seq);
    if (tmp <= max_mismatch)
    {
        if (tmp < sml1st)
        {
            sml1st = tmp;
            closest_match = barcode;
        }
        else if (sml1st < tmp && tmp <= sml2ed)
        {
            sml2ed = tmp;
        }
    }

It looks like `sml2ed = tmp` is only ever set if `sml1st < tmp` and so if `sml2ed` is ever set then `sml1st < sml2ed`. So the condition in the return

    if (sml1st < sml2ed)
    {
        return closest_match;
    }
    else
    {
        return string();
    }

can only return the empty string if both `sml1st` and `sml2ed` are never changed from their default values of `99999`. Can you check over this logic to see if it's doing what you want it to do?

**Comment by LuyiTian** [comment]
https://github.com/LuyiTian/scPipe/commit/3782f6f63f367890dc0337089c211cc007af04f9 yes you are right. Thank you for pointing out. I hope this commit will fix the problem
