### ISSUE TITLE
ERROR: compilation failed for package ‘scPipe’ in Centos7.3

### ISSUE THREAD

**Issue by xiewz** [LuyiTian/scPipe#99]
hi,
  I install the scPipe in Centos7.3, with the R version = 3.5.0, but failed in all different install methods.
  One of the install style is : R CMD INSTALL scPipe_1.2.1.tar.gz, and the error msg is:

[wzxie@localhost R-relate]$ R CMD INSTALL scPipe_1.2.1.tar.gz 
* installing to library ‘/home/wzxie/Rlibrary’
* installing *source* package ‘scPipe’ ...
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/wzxie/Rlibrary/Rcpp/include" -I"/home/wzxie/Rlibrary/Rhtslib/include" -I"/home/wzxie/Rlibrary/zlibbioc/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c Gene.cpp -o Gene.o
Gene.cpp: In member function ‘void Gene::flatten_exon()’:
Gene.cpp:103:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (auto i = 1; i < exon_vec.size(); i++)
                                        ^
Gene.cpp: In function ‘std::ostream& operator<<(std::ostream&, const Gene&)’:
Gene.cpp:128:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < obj.exon_vec.size(); ++i)
                                           ^
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/wzxie/Rlibrary/Rcpp/include" -I"/home/wzxie/Rlibrary/Rhtslib/include" -I"/home/wzxie/Rlibrary/zlibbioc/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c Interval.cpp -o Interval.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/wzxie/Rlibrary/Rcpp/include" -I"/home/wzxie/Rlibrary/Rhtslib/include" -I"/home/wzxie/Rlibrary/zlibbioc/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/wzxie/Rlibrary/Rcpp/include" -I"/home/wzxie/Rlibrary/Rhtslib/include" -I"/home/wzxie/Rlibrary/zlibbioc/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c cellbarcode.cpp -o cellbarcode.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/wzxie/Rlibrary/Rcpp/include" -I"/home/wzxie/Rlibrary/Rhtslib/include" -I"/home/wzxie/Rlibrary/zlibbioc/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c detect_barcode.cpp -o detect_barcode.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/wzxie/Rlibrary/Rcpp/include" -I"/home/wzxie/Rlibrary/Rhtslib/include" -I"/home/wzxie/Rlibrary/zlibbioc/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c parsebam.cpp -o parsebam.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/wzxie/Rlibrary/Rcpp/include" -I"/home/wzxie/Rlibrary/Rhtslib/include" -I"/home/wzxie/Rlibrary/zlibbioc/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c parsecount.cpp -o parsecount.o
parsecount.cpp: In function ‘void write_stat(std::string, std::string, std::vector<int>, std::unordered_map<std::basic_string<char>, UMI_dedup_stat>)’:
parsecount.cpp:134:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i=0; i<UMI_dup_count.size(); i++)
                                        ^
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/wzxie/Rlibrary/Rcpp/include" -I"/home/wzxie/Rlibrary/Rhtslib/include" -I"/home/wzxie/Rlibrary/zlibbioc/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c rcpp_scPipe_func.cpp -o rcpp_scPipe_func.o
In file included from rcpp_scPipe_func.cpp:7:0:
transcriptmapping.h: In member function ‘void GeneBin::add_gene(Gene)’:
transcriptmapping.h:41:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (gene.st < start)
                       ^
transcriptmapping.h:45:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (gene.en > end)
                       ^
transcriptmapping.h: In member function ‘const bool GeneBin::overlaps(const Interval&)’:
transcriptmapping.h:53:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return !(start > it.en) && !(end < it.st);
                             ^
transcriptmapping.h:53:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return !(start > it.en) && !(end < it.st);
                                               ^
In file included from config_hts.h:8:0,
                 from trimbarcode.h:6,
                 from rcpp_scPipe_func.cpp:3:
trimbarcode.h: At global scope:
/home/wzxie/Rlibrary/Rhtslib/include/kseq.h:170:16: warning: ‘kseq_t* kseq_init(gzFile)’ defined but not used [-Wunused-function]
  SCOPE kseq_t *kseq_init(type_t fd)         \
                ^
/home/wzxie/Rlibrary/Rhtslib/include/kseq.h:241:2: note: in expansion of macro ‘__KSEQ_BASIC’
  __KSEQ_BASIC(SCOPE, type_t)     \
  ^
/home/wzxie/Rlibrary/Rhtslib/include/kseq.h:244:35: note: in expansion of macro ‘KSEQ_INIT2’
 #define KSEQ_INIT(type_t, __read) KSEQ_INIT2(static, type_t, __read)
                                   ^
trimbarcode.h:11:1: note: in expansion of macro ‘KSEQ_INIT’
 KSEQ_INIT(gzFile, gzread)
 ^
/home/wzxie/Rlibrary/Rhtslib/include/kseq.h:176:13: warning: ‘void kseq_destroy(kseq_t*)’ defined but not used [-Wunused-function]
  SCOPE void kseq_destroy(kseq_t *ks)         \
             ^
/home/wzxie/Rlibrary/Rhtslib/include/kseq.h:241:2: note: in expansion of macro ‘__KSEQ_BASIC’
  __KSEQ_BASIC(SCOPE, type_t)     \
  ^
/home/wzxie/Rlibrary/Rhtslib/include/kseq.h:244:35: note: in expansion of macro ‘KSEQ_INIT2’
 #define KSEQ_INIT(type_t, __read) KSEQ_INIT2(static, type_t, __read)
                                   ^
trimbarcode.h:11:1: note: in expansion of macro ‘KSEQ_INIT’
 KSEQ_INIT(gzFile, gzread)
 ^
/home/wzxie/Rlibrary/Rhtslib/include/kseq.h:190:12: warning: ‘int kseq_read(kseq_t*)’ defined but not used [-Wunused-function]
  SCOPE int kseq_read(kseq_t *seq) \
            ^
/home/wzxie/Rlibrary/Rhtslib/include/kseq.h:242:2: note: in expansion of macro ‘__KSEQ_READ’
  __KSEQ_READ(SCOPE)
  ^
/home/wzxie/Rlibrary/Rhtslib/include/kseq.h:244:35: note: in expansion of macro ‘KSEQ_INIT2’
 #define KSEQ_INIT(type_t, __read) KSEQ_INIT2(static, type_t, __read)
                                   ^
trimbarcode.h:11:1: note: in expansion of macro ‘KSEQ_INIT’
 KSEQ_INIT(gzFile, gzread)
 ^
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/home/wzxie/Rlibrary/Rcpp/include" -I"/home/wzxie/Rlibrary/Rhtslib/include" -I"/home/wzxie/Rlibrary/zlibbioc/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c transcriptmapping.cpp -o transcriptmapping.o
In file included from transcriptmapping.cpp:2:0:
transcriptmapping.h: In member function ‘void GeneBin::add_gene(Gene)’:
transcriptmapping.h:41:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (gene.st < start)
                       ^
transcriptmapping.h:45:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (gene.en > end)
                       ^
transcriptmapping.h: In member function ‘const bool GeneBin::overlaps(const Interval&)’:
transcriptmapping.h:53:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return !(start > it.en) && !(end < it.st);
                             ^
transcriptmapping.h:53:47: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         return !(start > it.en) && !(end < it.st);
                                               ^
transcriptmapping.cpp: In member function ‘int Mapping::map_exon(bam_hdr_t*, bam1_t*, std::string&, bool)’:
transcriptmapping.cpp:464:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int c=0; c<b->core.n_cigar; c++)
                             ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from transcriptmapping.h:4,
                 from transcriptmapping.cpp:2:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_RandomAccessIterator std::__unguarded_partition(_RandomAccessIterator, _RandomAccessIterator, const _Tp&, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Gene*, std::vector<Gene> >; _Tp = Gene; _Compare = GeneAnnotation::parse_gff3_annotation(std::string, bool)::__lambda0]’:
/usr/include/c++/4.8.2/bits/stl_algo.h:2296:78:   required from ‘_RandomAccessIterator std::__unguarded_partition_pivot(_RandomAccessIterator, _RandomAccessIterator, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Gene*, std::vector<Gene> >; _Compare = GeneAnnotation::parse_gff3_annotation(std::string, bool)::__lambda0]’
/usr/include/c++/4.8.2/bits/stl_algo.h:2337:62:   required from ‘void std::__introsort_loop(_RandomAccessIterator, _RandomAccessIterator, _Size, _Compare) [with _RandomAccessIterator = __gnu_cxx::__normal_iterator<Gene*, std::vector<Gene> >; _Size = long int; _Compare = GeneAnnotation::parse_gff3_annotation(std::string, bool)::__lambda0]’
/usr/include/c++/4.8.2/bits/stl_algo.h:5499:44:   required from ‘void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter = __gnu_cxx::__normal_iterator<Gene*, std::vector<Gene> >; _Compare = GeneAnnotation::parse_gff3_annotation(std::string, bool)::__lambda0]’
transcriptmapping.cpp:338:9:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: **error: no match for call to ‘(GeneAnnotation::parse_gff3_annotation(std::string, bool)::__lambda0) (Gene&, const Gene&)**’
    while (__comp(*__first, __pivot))
                                   ^
transcriptmapping.cpp:337:14: note: candidates are:
             [] (Gene &g1, Gene &g2) { return g1.st < g2.st; }
              ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from transcriptmapping.h:4,
                 from transcriptmapping.cpp:2:
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note: bool (*)(Gene&, Gene&) <conversion>
    while (__comp(*__first, __pivot))
                                   ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2263:35: note:   candidate expects 3 arguments, 3 provided
transcriptmapping.cpp:337:35: note: GeneAnnotation::parse_gff3_annotation(std::string, bool)::__lambda0
             [] (Gene &g1, Gene &g2) { return g1.st < g2.st; }
                                   ^
transcriptmapping.cpp:337:35: note:   no known conversion for argument 2 from ‘const Gene’ to ‘Gene&’
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from transcriptmapping.h:4,
                 from transcriptmapping.cpp:2:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: **error: no match for call to ‘(GeneAnnotation::parse_gff3_annotation(std::string, bool)::__lambda0) (const Gene&, Gene&)’**
    while (__comp(__pivot, *__last))
                                  ^
transcriptmapping.cpp:337:14: note: candidates are:
             [] (Gene &g1, Gene &g2) { return g1.st < g2.st; }
              ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from transcriptmapping.h:4,
                 from transcriptmapping.cpp:2:
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note: bool (*)(Gene&, Gene&) <conversion>
    while (__comp(__pivot, *__last))
                                  ^
/usr/include/c++/4.8.2/bits/stl_algo.h:2266:34: note:   candidate expects 3 arguments, 3 provided
transcriptmapping.cpp:337:35: note: GeneAnnotation::parse_gff3_annotation(std::string, bool)::__lambda0
             [] (Gene &g1, Gene &g2) { return g1.st < g2.st; }
                                   ^
transcriptmapping.cpp:337:35: note:   no known conversion for argument 1 from ‘const Gene’ to ‘Gene&’
transcriptmapping.cpp: In member function ‘void Mapping::parse_align(std::string, std::string, bool, std::string, std::string, std::string, std::string, int, int)’:
transcriptmapping.cpp:605:30: warning: ignoring return value of ‘int sam_hdr_write(samFile*, const bam_hdr_t*)’, declared with attribute warn_unused_result [-Wunused-result]
     sam_hdr_write(of, header);
                              ^
make: *** [transcriptmapping.o] Error 1
**ERROR: compilation failed for package ‘scPipe’**
* removing ‘/home/wzxie/Rlibrary/scPipe’

**Comment by Shians** [comment]
You can try to install the developmental version using

```
install.packages("devtools")
devtools::install_github("LuyiTian/scPipe")
```

That bug is likely the same one as [this one](https://github.com/LuyiTian/scPipe/issues/94). It's an issue with version 4.8.2 of gcc.

**Comment by xiewz** [comment]
> You can try to install the developmental version using
> 
> ```
> install.packages("devtools")
> devtools::install_github("LuyiTian/scPipe")
> ```
> That bug is likely the same one as [this one](https://github.com/LuyiTian/scPipe/issues/94). It's an issue with version 4.8.2 of gcc.

Tks! That did the trick.  I installed the rhtslib via devtools first `devtools::install_github("bioconductor/rhtslib")`， then intall the scPipe successfully.
